package com.nttdata.model.am;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 07 00:12:44 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CoreHRMainAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CoreHRMainAMImpl() {
    }

    /**
     * Container's getter for CountriesVO1.
     * @return CountriesVO1
     */
    public ViewObjectImpl getCountriesVO1() {
        return (ViewObjectImpl)findViewObject("CountriesVO1");
    }

    /**
     * Container's getter for DepartmentsVO1.
     * @return DepartmentsVO1
     */
    public ViewObjectImpl getDepartmentsVO1() {
        return (ViewObjectImpl)findViewObject("DepartmentsVO1");
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public ViewObjectImpl getEmployeesVO1() {
        return (ViewObjectImpl)findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for JobHistoryVO1.
     * @return JobHistoryVO1
     */
    public ViewObjectImpl getJobHistoryVO1() {
        return (ViewObjectImpl)findViewObject("JobHistoryVO1");
    }

    /**
     * Container's getter for JobsVO1.
     * @return JobsVO1
     */
    public ViewObjectImpl getJobsVO1() {
        return (ViewObjectImpl)findViewObject("JobsVO1");
    }

    /**
     * Container's getter for LocationsVO1.
     * @return LocationsVO1
     */
    public ViewObjectImpl getLocationsVO1() {
        return (ViewObjectImpl)findViewObject("LocationsVO1");
    }

    /**
     * Container's getter for RegionsVO1.
     * @return RegionsVO1
     */
    public ViewObjectImpl getRegionsVO1() {
        return (ViewObjectImpl)findViewObject("RegionsVO1");
    }

    /**
     * Container's getter for DepartmentsVO2.
     * @return DepartmentsVO2
     */
    public ViewObjectImpl getDepartmentsVO2() {
        return (ViewObjectImpl)findViewObject("DepartmentsVO2");
    }

    /**
     * Container's getter for EmployeesVO2.
     * @return EmployeesVO2
     */
    public ViewObjectImpl getEmployeesVO2() {
        return (ViewObjectImpl)findViewObject("EmployeesVO2");
    }

    /**
     * Container's getter for EmployeesVO3.
     * @return EmployeesVO3
     */
    public ViewObjectImpl getEmployeesVO3() {
        return (ViewObjectImpl)findViewObject("EmployeesVO3");
    }

    /**
     * Container's getter for EmployeesVO4.
     * @return EmployeesVO4
     */
    public ViewObjectImpl getEmployeesVO4() {
        return (ViewObjectImpl)findViewObject("EmployeesVO4");
    }

    /**
     * Container's getter for JobHistoryVO2.
     * @return JobHistoryVO2
     */
    public ViewObjectImpl getJobHistoryVO2() {
        return (ViewObjectImpl)findViewObject("JobHistoryVO2");
    }

    /**
     * Container's getter for JobHistoryVO3.
     * @return JobHistoryVO3
     */
    public ViewObjectImpl getJobHistoryVO3() {
        return (ViewObjectImpl)findViewObject("JobHistoryVO3");
    }

    /**
     * Container's getter for JobHistoryVO4.
     * @return JobHistoryVO4
     */
    public ViewObjectImpl getJobHistoryVO4() {
        return (ViewObjectImpl)findViewObject("JobHistoryVO4");
    }

    /**
     * Container's getter for DepartmentsVO3.
     * @return DepartmentsVO3
     */
    public ViewObjectImpl getDepartmentsVO3() {
        return (ViewObjectImpl)findViewObject("DepartmentsVO3");
    }

    /**
     * Container's getter for DeptMgrFkLink1.
     * @return DeptMgrFkLink1
     */
    public ViewLinkImpl getDeptMgrFkLink1() {
        return (ViewLinkImpl)findViewLink("DeptMgrFkLink1");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink1");
    }

    /**
     * Container's getter for EmpJobFkLink1.
     * @return EmpJobFkLink1
     */
    public ViewLinkImpl getEmpJobFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpJobFkLink1");
    }

    /**
     * Container's getter for JhistDeptFkLink1.
     * @return JhistDeptFkLink1
     */
    public ViewLinkImpl getJhistDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("JhistDeptFkLink1");
    }

    /**
     * Container's getter for JhistEmpFkLink1.
     * @return JhistEmpFkLink1
     */
    public ViewLinkImpl getJhistEmpFkLink1() {
        return (ViewLinkImpl)findViewLink("JhistEmpFkLink1");
    }

    /**
     * Container's getter for JhistJobFkLink1.
     * @return JhistJobFkLink1
     */
    public ViewLinkImpl getJhistJobFkLink1() {
        return (ViewLinkImpl)findViewLink("JhistJobFkLink1");
    }

    /**
     * Container's getter for DeptLocFkLink1.
     * @return DeptLocFkLink1
     */
    public ViewLinkImpl getDeptLocFkLink1() {
        return (ViewLinkImpl)findViewLink("DeptLocFkLink1");
    }


    /**
     * Container's getter for CountriesVO2.
     * @return CountriesVO2
     */
    public ViewObjectImpl getCountriesVO2() {
        return (ViewObjectImpl)findViewObject("CountriesVO2");
    }

    /**
     * Container's getter for LocationsCountriesLink1.
     * @return LocationsCountriesLink1
     */
    public ViewLinkImpl getLocationsCountriesLink1() {
        return (ViewLinkImpl)findViewLink("LocationsCountriesLink1");
    }
}
